export const GET_FRIEND_LIST_PENDING = 'GET_FRIEND_LIST_PENDING';
export const GET_FRIEND_LIST_SUCCESS = 'GET_FRIEND_LIST_SUCCESS';
export const GET_FRIEND_LIST_FAILED = 'GET_FRIEND_LIST_FAILED';

export const GET_FRIEND_POST_LIST_PENDING = 'GET_FRIEND_POST_LIST_PENDING';
export const GET_FRIEND_POST_LIST_SUCCESS = 'GET_FRIEND_POST_LIST_SUCCESS';
export const GET_FRIEND_POST_LIST_FAILED = 'GET_FRIEND_POST_LIST_FAILED';

export const GET_FRIEND_ALBUM_LIST_PENDING = 'GET_FRIEND_ALBUM_LIST_PENDING';
export const GET_FRIEND_ALBUM_LIST_SUCCESS = 'GET_FRIEND_ALBUM_LIST_SUCCESS';
export const GET_FRIEND_ALBUM_LIST_FAILED = 'GET_FRIEND_ALBUM_LIST_FAILED';