export const PENDING = 'PENDING';
export const FAILED = 'FAILED';

export const GET_FRIEND_LIST_SUCCESS = 'GET_FRIEND_LIST_SUCCESS';

export const GET_FRIEND_POST_LIST_SUCCESS = 'GET_FRIEND_POST_LIST_SUCCESS';
export const GET_FRIEND_POST_COMMENT_LIST_SUCCESS = 'GET_FRIEND_POST_COMMENT_LIST_SUCCESS';

export const GET_FRIEND_ALBUM_LIST_SUCCESS = 'GET_FRIEND_ALBUM_LIST_SUCCESS';
export const GET_FRIEND_ALBUM_PHOTOS_LIST_SUCCESS = 'GET_FRIEND_ALBUM_PHOTOS_LIST_SUCCESS';

export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const ADD_NEW_COMMENT_SUCCESS = 'ADD_NEW_COMMENT_SUCCESS';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

export const ADD_NEW_FRIEND_COMMENT_SUCCESS = 'ADD_NEW_FRIEND_COMMENT_SUCCESS';
export const UPDATE_FRIEND_COMMENT_SUCCESS = 'UPDATE_FRIEND_COMMENT_SUCCESS';
export const DELETE_FRIEND_COMMENT_SUCCESS = 'DELETE_FRIEND_COMMENT_SUCCESS';



/*
export const PENDING = 'PENDING';
export const FAILED = 'FAILED';

export const GET_FRIEND_LIST_SUCCESS = 'GET_FRIEND_LIST_SUCCESS';

export const GET_FRIEND_POST_LIST_PENDING = 'GET_FRIEND_POST_LIST_PENDING';
export const GET_FRIEND_POST_LIST_SUCCESS = 'GET_FRIEND_POST_LIST_SUCCESS';
export const GET_FRIEND_POST_LIST_FAILED = 'GET_FRIEND_POST_LIST_FAILED';

export const GET_FRIEND_POST_COMMENT_LIST_PENDING = 'GET_FRIEND_POST_COMMENT_LIST_PENDING';
export const GET_FRIEND_POST_COMMENT_LIST_SUCCESS = 'GET_FRIEND_POST_COMMENT_LIST_SUCCESS';
export const GET_FRIEND_POST_COMMENT_LIST_FAILED = 'GET_FRIEND_POST_COMMENT_LIST_FAILED';

export const GET_FRIEND_ALBUM_LIST_PENDING = 'GET_FRIEND_ALBUM_LIST_PENDING';
export const GET_FRIEND_ALBUM_LIST_SUCCESS = 'GET_FRIEND_ALBUM_LIST_SUCCESS';
export const GET_FRIEND_ALBUM_LIST_FAILED = 'GET_FRIEND_ALBUM_LIST_FAILED';

export const GET_FRIEND_ALBUM_PHOTOS_LIST_PENDING = 'GET_FRIEND_ALBUM_PHOTOS_LIST_PENDING';
export const GET_FRIEND_ALBUM_PHOTOS_LIST_SUCCESS = 'GET_FRIEND_ALBUM_PHOTOS_LIST_SUCCESS';
export const GET_FRIEND_ALBUM_PHOTOS_LIST_FAILED = 'GET_FRIEND_ALBUM_PHOTOS_LIST_FAILED';

export const ADD_NEW_POST_PENDING = 'ADD_NEW_POST_PENDING';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAILED = 'ADD_NEW_POST_FAILED';

export const UPDATE_POST_PENDING = 'UPDATE_POST_PENDING';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED';

export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const ADD_NEW_COMMENT_PENDING = 'ADD_NEW_COMMENT_PENDING';
export const ADD_NEW_COMMENT_SUCCESS = 'ADD_NEW_COMMENT_SUCCESS';
export const ADD_NEW_COMMENT_FAILED = 'ADD_NEW_COMMENT_FAILED';

export const UPDATE_COMMENT_PENDING = 'UPDATE_COMMENT_PENDING';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAILED = 'UPDATE_COMMENT_FAILED';

export const DELETE_COMMENT_PENDING = 'DELETE_COMMENT_PENDING';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const ADD_NEW_FRIEND_COMMENT_PENDING = 'ADD_NEW_FRIEND_COMMENT_PENDING';
export const ADD_NEW_FRIEND_COMMENT_SUCCESS = 'ADD_NEW_FRIEND_COMMENT_SUCCESS';
export const ADD_NEW_FRIEND_COMMENT_FAILED = 'ADD_NEW_FRIEND_COMMENT_FAILED';

export const UPDATE_FRIEND_COMMENT_PENDING = 'UPDATE_FRIEND_COMMENT_PENDING';
export const UPDATE_FRIEND_COMMENT_SUCCESS = 'UPDATE_FRIEND_COMMENT_SUCCESS';
export const UPDATE_FRIEND_COMMENT_FAILED = 'UPDATE_FRIEND_COMMENT_FAILED';

export const DELETE_FRIEND_COMMENT_PENDING = 'DELETE_FRIEND_COMMENT_PENDING';
export const DELETE_FRIEND_COMMENT_SUCCESS = 'DELETE_FRIEND_COMMENT_SUCCESS';
export const DELETE_FRIEND_COMMENT_FAILED = 'DELETE_FRIEND_COMMENT_FAILED';
*/